### ISSUE TITLE
Question: Why do you need my browser history?

### ISSUE THREAD

**Issue by ent3r** [softvar/enhanced-github#50]
I just got a notification from chrome saying enhanced github has been disabled due to new permissions. It asks me if i want to give the extension permissions to read my browser history. Why?

**Comment by ent3r** [comment]
@softvar Tagging you as this is important

**Comment by softvar** [comment]
@ent3r Thanks for showing your genuine concern. I appreciate your concern regarding privacy.
This extension doesn't require any `history` API. But, lately, I have used `webNavigation` API for GitHub being single-page application now.

See the list of permissions required in `manifest file`:  https://github.com/softvar/enhanced-github/blob/master/manifest.json#L19
[permssions required and why](https://github.com/softvar/enhanced-github#permissions-required)

Why is `webNavigation` related to `history` API? https://developer.chrome.com/extensions/webNavigation#event-onHistoryStateUpdated

Check the code being used: https://github.com/softvar/enhanced-github/blob/master/src/background.js

`webNavigation` API is generic but I have used URL event filters to know when a page-url is changed on GitHub website. This is required because GitHub is now a single-page-application. And to keep getting the benefits, I had to support SPA behavior.

Here's the article I wrote which mentions the reason for introducing new permissions.
https://medium.com/@softvar/making-chrome-extension-smart-by-supporting-spa-websites-1f76593637e8

Rest assured, the code is open-sourced. There's no intention of requesting unwanted permissions. 
If you have any suggestions on how to handle GitHub SPA website without `webNavigation` API, I would be happy to discuss it.

**Comment by ent3r** [comment]
Thanks for clearing this up :) Great extension!
